### ISSUE TITLE
Update README.md of the repository. 

### ISSUE THREAD

**Issue by aditya-singh9** [genicsblog/genicsblog.com#106]
Update the README.md of this repository because there is nothing which tells about what is genicsblog and why you should use genicsblog etc.

**Comment by gouravkhunger** [comment]
I've added the [organisation profile](https://github.com/genicsblog/.github/tree/main/profile). Will be adding some info to this repo's README soon!

**Comment by gouravkhunger** [comment]
Of course @AnishDe12020! You may take some ideas from [docs](https://docs.genicsblog.com/developer). They are not really complete, but might give some insights. Do you have any ideas on what could make it look better?

**Comment by AnishDe12020** [comment]
For the Local Setup part, I will make some modifications to how to handle errors (like running `chmod` only for permission issues else opening an issue on gh or reaching out on discord). Local Setup can also be renamed to contributing with some basic guidelines. I will also add a larger description for the repo and explain the structure and stuff. Let me make the pr and then I can make any changes as required

**Comment by gouravkhunger** [comment]
Alright!
