### ISSUE TITLE
Solidity Quickstart - Part 1 

### ISSUE THREAD

**Issue by Kira272921** [genicsblog/genicsblog.com#113]
### Idea
An article which covers the basics of solidity, like how to create your first smart contract, data types and variables

### Topics

**Category**: web-development

**Tags**: web3, solidity, blockchain

### Cross-posting?
**Yes**
https://blog.kiradev.co/solidity-quickstart-0

**Comment by gouravkhunger** [comment]
Great post, you're welcome to add the draft 😄

**Comment by Kira272921** [comment]
Alright, will create a draft tomorrow morning 😄
