### ISSUE TITLE
New Article Submission Request

### ISSUE THREAD

**Issue by max-programming** [genicsblog/genicsblog.com#118]
### Idea
The article is about formatting import statements in a JavaScript project using Prettier in VS Code

### Topics

**Category**: Clean Code

**Tags**: Prettier, VS Code

### Cross-posting?

https://blog.usman-s.me/sort-imports-using-prettier-in-a-javascript-project-inside-vs-code

**Comment by max-programming** [comment]
Here's [my draft](https://github.com/max-programming/genicsblog.github.io/blob/main/_drafts/2022-03-23-sort-imports-using-prettier-in-a-javascript-project-inside-vs-code.md)

Should I make a pull request for it?

**Comment by gouravkhunger** [comment]
Sure @max-programming, would love to see your draft! 

Just one thing, do rename your fork from `genicsblog.github.io` to `genicsblog.com` so that the PR checks don't fail because of different fork name :)

**Comment by max-programming** [comment]
Gotcha!
