### ISSUE TITLE
Cross blog this blog post

### ISSUE THREAD

**Issue by Bennykillua** [genicsblog/genicsblog.com#124]
### Idea
In this article, I will share with you what I discovered and also mention some non-code ways you can contribute, open-source projects you can contribute to, and helpful resources.

### Topics

**Open Source**: 

**Beginner guide, non-tech, Open source**: 

### Cross-posting?

 https://benny.hashnode.dev/how-to-contribute-to-open-source-projects-as-a-non-coder

### Remarks

 My Social media: [Twitter](https://twitter.com/bennykillua) ,  [Linkedin](https://www.linkedin.com/in/ifeanyi-iheagwara/)

**Comment by gouravkhunger** [comment]
Hey @Bennykillua, thanks for your interest in posting your article here!
I gave your article a read and enjoyed it!

To get started- you'd need to get a profile (one time task). Please follow [this guide](https://docs.genicsblog.com/author/configure-your-profile) to do the same. We understand that not all people are familiar with open source procedures, so we're ready to help you at every stage! You might want to consider [joining us at discord](https://discord.genicsblog.com) to get help.

Reading [this article](https://genicsblog.com/gouravkhunger/how-to-create-a-pull-request-in-github-correctly) would help too.

Thanks for your time!

**Comment by Bennykillua** [comment]
Done. Thanks @gouravkhunger

**Comment by gouravkhunger** [comment]
@Bennykillua there was some issue in PR checks, but you didn't need to close and remake the PR. No problem, I will review the error asap and get your changes merged!

Thanks!

**Comment by gouravkhunger** [comment]
Thanks for making your profile! Now you can create a markdown file with the draft version. [Here](https://docs.genicsblog.com/author/writing-the-article) are the docs to help with that. You can use some [custom UI elements](https://docs.genicsblog.com/author/ui-components) which we built especially for Genics.

Let me know if you need some help :)

**Comment by Bennykillua** [comment]
I just submitted the draft @gouravkhunger 

PR [link](https://github.com/genicsblog/genicsblog.com/pull/127)

**Comment by gouravkhunger** [comment]
Great, the draft was merged! I'll review and publish it soon :)

It's done on your part now. Thanks!

**Comment by gouravkhunger** [comment]
Hey @Bennykillua!

[The post](https://genicsblog.com/benny/no-code-ways-to-contribute-to-open-source-projects) was published 🥳. We are aware that the underline animation for links aren't properly rendering on mobile screens. We'll fix this soon.

Congrats on your first contribution 🎉 

It would be great to gain feedback from you on how we can improve [genicsblog.com](https://genicsblog.com)! Please drop it here in the comments or our [discord server](https://discord.genicsblog.com) :)
