### ISSUE TITLE
New Article Submission Request

### ISSUE THREAD

**Issue by max-programming** [genicsblog/genicsblog.com#129]
### Idea
The article is about setting up Mongoose with Next.js with a simple project tutorial

### Topics

**Category**: coding

**Tags**: nextjs, reactjs, mongodb

### Cross-posting?
https://blog.usman-s.me/how-to-use-mongoose-with-nextjs-for-mongodb

**Comment by gouravkhunger** [comment]
[Here](https://genicsblog.com/usman/how-to-use-mongoose-with-next-js-for-mongodb) you go 🚀 

Thanks for the amazing article! 😄
