### ISSUE TITLE
feat: new article submission "How to build a faucet CLI using NodeJS"

### ISSUE THREAD

**Issue by Kira272921** [genicsblog/genicsblog.com#133]
### Idea
Building a faucet CLI using NodeJS which would send testnet tokens to the user on request. The CLI would also have metamask authentication

### Topics

web3, blockchain, cli, nodejs

**Category**: nodejs

**Tags**: web3, blockchain, nodejs

### Cross-posting?

Yes. https://blog.kiradev.co/how-to-build-a-faucet-cli-using-nodejs

**Comment by gouravkhunger** [comment]
Very Informative! You're welcome to submit a PR :)

Btw, does it require any more languages than the [theme supports](https://docs.genicsblog.com/author/ui-components#code-blocks)?

**Comment by Kira272921** [comment]
@gouravkhunger It doesn't require any more languages :D

**Comment by gouravkhunger** [comment]
Great, looking forward to the PR!
