### ISSUE TITLE
Post: Sessions vs JWTs - A Complete Guide to Authentication

### ISSUE THREAD

**Issue by carrotfarmer** [genicsblog/genicsblog.com#140]
https://blog.dhruva.is-a.dev/sessions-vs-jwts-a-complete-guide-to-authentication
Cross-post ^

**Comment by gouravkhunger** [comment]
Awesome guide! Would love to see the PR. I have a question, how do you make these amazing graphics?

![image](https://user-images.githubusercontent.com/46792249/168003814-8af44592-2977-4529-b6c8-3c28de924941.png)

**Comment by gouravkhunger** [comment]
They look amazing!

**Comment by carrotfarmer** [comment]
Thanks! @gouravkhunger I made them using [Excalidraw](https://excalidraw.com)

**Comment by gouravkhunger** [comment]
Amazing!
