### ISSUE TITLE
feature: a front matter generator tool for drafts

### ISSUE THREAD

**Issue by kr-anurag** [genicsblog/genicsblog.com#93]
A simple tool, preferably in the form of a website to generate the front matter for drafts.

PS: you can refer this tool on the genicsblog website

**Comment by gouravkhunger** [comment]
btw, It's also searchable from the searchbar

<img width="687" alt="image" src="https://user-images.githubusercontent.com/46792249/166068279-f900917b-efa0-4231-a3ee-75215970c13a.png">

**Comment by shockz09** [comment]
GG

**Comment by kr-anurag** [comment]
p nice!! GGs 🚀
