### ISSUE TITLE
How to build a blog using Remix and MDX

### ISSUE THREAD

**Issue by Kira272921** [genicsblog/genicsblog.com#94]
### Idea
A blog post explaining how to build a blog site using the new javascript framework, [Remix](https://remix.run), MDX and TailwindCSS

### Topics

**Category**: web

**Tags**: web-development, beginners

### Cross-posting?
Yes

https://kirablog.hashnode.dev/build-a-blog-using-remix-and-mdx

**Comment by gouravkhunger** [comment]
Just went through the post, I like it :)
I might be opinionated because Jekyll is similar in regards to the writing process (markdown with frontmatter) and that's what we use all the time here at @genicsblog :P

You can submit a draft 😄

**Comment by gouravkhunger** [comment]
Published! [Here's](https://genicsblog.com/kira/how-to-build-a-blog-using-remix-and-mdx) the link
