### ISSUE TITLE
Article Idea: 15 less-known and underrated HTML tags for web developers

### ISSUE THREAD

**Issue by RainboeStrykr** [genicsblog/genicsblog.com#95]
### Idea
There are a few lesser-known HTML attributes that are easy to learn and can help you to achieve common tasks, which would otherwise be fulfilled using some external libraries.

### Topics

**Category**: web

**Tags**: web-development, tips, beginners

### Cross-posting?

NO

**Comment by gouravkhunger** [comment]
Great, would love to see the draft post 😄
You can go ahead 👍🏻

**Comment by gouravkhunger** [comment]
Thanks, [your article](https://genicsblog.com/underrated-html-attributes-every-webdev-should-know) was published!
