### ISSUE TITLE
GitHub Repositories to Crush any Programming Interview

### ISSUE THREAD

**Issue by Ghxst07** [genicsblog/genicsblog.com#96]
### Idea
GitHub Repositories to Crush any Programming Interview

### Topics

**Category**: Programming Interviews

**Tags**: Programming Interviews, Software development, Beginners 

### Cross-posting?

NO

### Remarks
Will contain repositories of various git-hub users. These repositories has been selected based on popularity, usage and other similar lists.

**Comment by Kushagra-Jain99** [comment]
Hey, thanks for the request!

I had a few questions:
- how many repositories are you willing to feature in the post? 
- Will there be some kind of graphic images, like screenshots of README files of the repositories, for better accessibility for the readers.
- Would you write some 100-200 words for each repo?

The topic seems good, but to make it look interesting we could work on the above points! Once we clarify the above, we will tell you the next steps!

**Comment by Ghxst07** [comment]
Hi,
So here are the answers :
1. It will feature 10 repos.
2. There will be screenshots under the hyperlinks.
3. I would be writing about the repos in points. If they are joined together it'll be around 100 to 150 words I suppose.

**Comment by Ghxst07** [comment]
> Hey, thanks for the request!
> 
> I had a few questions:
> 
> * how many repositories are you willing to feature in the post?
> * Will there be some kind of graphic images, like screenshots of README files of the repositories, for better accessibility for the readers.
> * Would you write some 100-200 words for each repo?
> 
> The topic seems good, but to make it look interesting we could work on the above points! Once we clarify the above, we will tell you the next steps!

Hi,
So here are the answers :
1. It will feature 10 repos.
2. There will be screenshots under the hyperlinks.
3. I would be writing about the repos in points. If they are joined together it'll be around 100 to 150 words I suppose.

**Comment by gouravkhunger** [comment]
Yes, 10 seems a good number.

For the screenshots, try to use a consistent color scheme for all screenshots, using [this app](https://pika.rishimohan.me/). It would look great.

You don't need to host the images manually. You can upload the images to the comments section here and GitHub will host it for you.

You can use any markdown app to write the draft. Once you feel your draft is ready, you can submit it by following [these steps](https://docs.genicsblog.com/author/writing-the-article). Good luck!

**Comment by gouravkhunger** [comment]
[The article](https://genicsblog.com/github-repositories-to-crush-any-programming-interview) is live!

Thanks for your first contribution :)
If you wish to be added to our google analytics stats for authors, you can get in touch at discord.
